# Set up the Hello World string
str="Hello M4650,"
# In python you can concatentate strings using the addition(+) operator
print(str + " my name is Varis Carey, and I'm the repo owner")
# Add your hello statment below this line of code
print(str + " my name is Robert Iordache and I'm a pusher, and I'm standing still.")
print(str + " my name is Cody Smith and I'm a pusher")
print(str + " my name is Andrew Bentley")
print(str + " my name is Yunzhou Li")
print(str + " my name is Liam Flannagan")
print(str + " my name is Ge Feng")
print(str + " my name is Tanner Juby, I am a pusher, and am standing still")
print(str + " my name is Will Rooney and I'm a pusher, and I'm standing still.")
print(str + " my name is Yujia Lu")
print(str + " my name is Chetan Sharma and I'm a pusher, and I'm standing still.")
print(str + " my name is Nikolai Sharp and I'm a pusher, and I'm standing still.")
print(str + " my name is Kaiqi Zhang")
print(str + " my name is Jianwei Zou")
print(str + " my name is Sean Adams and I'm a pusher")
print(str + " my name is Ed Salisbury")
print(str + " my name is Preston Trimble")
print(str + " my name is David Andrews and I'm a pusher, and I'm standing still.")
print(str + " my name is Cameron Bramwell")
print(str + " my name is Zack Foreman")
print(str + " my name is Gediminas Jakstonis")
print(str + " my name is Ramy Shim")
print(str + " my name is David Pontecorvo")
print(str + " my name is Quyen Nguyen")
print(str + " my name is Lily Dam")
print(str + "My name is Talia McFadden.")
